### ISSUE TITLE
Issue related to re-downloading if file is already present in the cache

### ISSUE THREAD

**Issue by bulolo** [nitinsh99/VeloxDownloader#20]
```
Also, if there is already a file present in the cache directory, VeloxDownloader removes the files and replaces the file.
```

when i download my file the second time(mean i finished the first file,and press the download button second time):
```
file1 got deleted : true
file is finished downloading
```
is this mean the second i download the file,it do not redownload the file from the remote url? instead it just replace the file?

then i reopen the app,the temp file deleted,and the cache file still exist,i press the download btn ,the file download from remote url and replace the file that in the cache file?

is that right above?

**Comment by nitinsh99** [comment]
Hi @bulolo 

Thanks for reporting this. I have identified and fixed the issue in version 1.6. Now downloading will occur every time and will either create a new file or will replace the existing file if it's present in the cache. Please download the version 1.6 of the VeloxDownloader. 

put following in your PodFile.
`pod 'VeloxDownloader', '~> 1.6'
`
and run `pod update` from terminal

Along with this I have also fixed an issue related to VeloxDownloader UI so if you want to try that you can see it in action by cloning and running this project. 

`git clone https://github.com/nitinsh99/VeloxDownloader.git
`
Please verify and let me know so we can close this issue.
